In [1]:
import os
import pandas as pd

In [4]:
csv_filename = 'Table_2.2_Residential_Sector_Energy_Consumption_monthly.csv'
full_path = os.path.join(r'C:\Users\tobia\OneDrive\Desktop\School\EIA_Residential_Energy_Consumption_Time_Series_Forecasting\data', csv_filename)
df_monthly = pd.read_csv(full_path)
df_monthly.head()

,Month,Coal Consumed by the Residential Sector,Natural Gas Consumed by the Residential Sector (Excluding Supplemental Gaseous Fuels),Petroleum Consumed by the Residential Sector,Total Fossil Fuels Consumed by the Residential Sector,Geothermal Energy Consumed by the Residential Sector,Solar Energy Consumed by the Residential Sector,Biomass Energy Consumed by the Residential Sector,Total Renewable Energy Consumed by the Residential Sector,Total Primary Energy Consumed by the Residential Sector,Electricity Sales to Ultimate Customers in the Residential Sector,End-Use Energy Consumed by the Residential Sector,Electricity System Energy Losses Proportioned to the Residential Sector,Total Energy Consumed by the Residential Sector
0,1973 January,11.894,860.778,436.556,1309.228,Not Available,Not Available,30.074,30.074,1339.302,180.291,1519.593,371.524,1891.117
1,1973 February,10.188,762.278,375.287,1147.753,Not Available,Not Available,27.164,27.164,1174.916,169.240,1344.156,310.563,1654.718
2,1973 March,8,661.474,283.839,953.313,Not Available,Not Available,30.074,30.074,983.386,158.027,1141.413,308.108,1449.521
3,1973 April,5.237,475.184,205.866,686.288,Not Available,Not Available,29.104,29.104,715.392,142.693,858.085,271.515,1129.600
4,1973 May,5.313,332.839,167.675,505.827,Not Available,Not Available,30.074,30.074,535.901,135.883,671.784,281.772,953.556

In [5]:
csv_filename = 'Table_2.2_Residential_Sector_Energy_Consumption_annual.csv'
full_path = os.path.join(r'C:\Users\tobia\OneDrive\Desktop\School\EIA_Residential_Energy_Consumption_Time_Series_Forecasting\data', csv_filename)
df_annual = pd.read_csv(full_path)
df_annual.head()

,Annual Total,Coal Consumed by the Residential Sector,Natural Gas Consumed by the Residential Sector (Excluding Supplemental Gaseous Fuels),Petroleum Consumed by the Residential Sector,Total Fossil Fuels Consumed by the Residential Sector,Geothermal Energy Consumed by the Residential Sector,Solar Energy Consumed by the Residential Sector,Biomass Energy Consumed by the Residential Sector,Total Renewable Energy Consumed by the Residential Sector,Total Primary Energy Consumed by the Residential Sector,Electricity Sales to Ultimate Customers in the Residential Sector,End-Use Energy Consumed by the Residential Sector,Electricity System Energy Losses Proportioned to the Residential Sector,Total Energy Consumed by the Residential Sector
0,1949,1271.551,1027.283,1106.568,3405.402,Not Available,Not Available,1055.186,1055.186,4460.588,227.894,4688.482,637.215,5325.697
1,1950,1261.267,1240.312,1322.420,3823.999,Not Available,Not Available,1005.529,1005.529,4829.528,246.348,5075.876,660.509,5736.385
2,1951,1158.679,1526.340,1461.449,4146.468,Not Available,Not Available,958.212,958.212,5104.680,283.513,5388.193,735.505,6123.698
3,1952,1079.206,1678.735,1501.301,4259.242,Not Available,Not Available,899.164,899.164,5158.406,319.175,5477.581,808.236,6285.817
4,1953,965.664,1744.496,1510.642,4220.802,Not Available,Not Available,831.947,831.947,5052.749,355.347,5408.096,888.745,6296.841